### ISSUE TITLE
Align the header with correct row data

### ISSUE THREAD

**Issue by SDSamarasinghe** [PasinduPrabhashitha/DS-Frontend#35]
![image](https://github.com/PasinduPrabhashitha/DS-Frontend/assets/73936634/06ff88fe-f96b-4db3-8800-3389365ec943)

**Comment by rAVINDUpRABASHWARA** [comment]
The issue is fixed.
![Screenshot 2023-05-17 151508](https://github.com/PasinduPrabhashitha/DS-Frontend/assets/78830875/b69aff6e-f4ea-476e-a5fc-666d80fa18cc)
